spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

app:
  url: "https://short.at"
